//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HopDong
    {
        public int MaHD { get; set; }
        public int MaNV { get; set; }
        public string LoaiHD { get; set; }
        public Nullable<System.DateTime> TuNgay { get; set; }
        public Nullable<System.DateTime> DenNgay { get; set; }
    
        public virtual tb_NhanVien tb_NhanVien { get; set; }
    }
}
